INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO ACCOUNT (ACTIVATED, EMAIL, GENDER, NICKNAME, PASSWORD, TEL, USERNAME, ACCOUNT_ID)
VALUES (TRUE, 'bangshinho@gmail.com', 'M', 'senob', '$2a$10$w6dkndLkiabxEJk/t.qzm.nZu3xfMEDOkX5Y82jjqNB63BZKSSKaC', 01028564617, 'BANGSHINHO', 1);

INSERT INTO ACCOUNT (ACTIVATED, EMAIL, GENDER, NICKNAME, PASSWORD, TEL, USERNAME, ACCOUNT_ID)
VALUES (TRUE, 'sample@gmail.com', 'M', 'senob', '$2a$10$w6dkndLkiabxEJk/t.qzm.nZu3xfMEDOkX5Y82jjqNB63BZKSSKaC', 01028564617, 'BANGSHINHO', 2);

INSERT INTO ACCOUNT_AUTHORITY (ACCOUNT_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');
INSERT INTO ACCOUNT_AUTHORITY (ACCOUNT_ID, AUTHORITY_NAME) VALUES (2, 'ROLE_USER');

INSERT INTO ORDERS (ORDER_ID, PRODUCT_NAME, PAYMENT_DATE, ACCOUNT_ID) VALUES (1, '아이디어스 행복한 세상', sysdate, 1);
INSERT INTO ORDERS (ORDER_ID, PRODUCT_NAME, PAYMENT_DATE, ACCOUNT_ID) VALUES (2, '아이디어스 캠핑초보를 위한 캠지기의 추천템!', sysdate, 1);
INSERT INTO ORDERS (ORDER_ID, PRODUCT_NAME, PAYMENT_DATE, ACCOUNT_ID) VALUES (3, '아이디어스 주식초보를 위한 강습 책!', sysdate, 2);